name: Close issues we are not able to help
# See https://github.com/marketplace/actions/issue-title-checker

on:
  issues:
    types: [opened]
jobs:   
  auto_close:
    runs-on: ubuntu-latest
    steps:
    - name: Well wishes
      uses: IndyV/IssueChecker@v1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-close-message: "Hope everyone finds the help they need."
        issue-pattern: "User: I'm looking for more help"
